# Generated by Django 4.1.6 on 2024-01-02 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pr',
            name='img',
        ),
        migrations.RemoveField(
            model_name='pr',
            name='name',
        ),
        migrations.AddField(
            model_name='pr',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pr',
            name='description',
            field=models.TextField(default='the movie is too good to experience'),
        ),
        migrations.AddField(
            model_name='pr',
            name='genre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='pr',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pr',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pr',
            name='title',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
